#!/bin/bash

# ─── hs-lp-generator installer ────────────────────────────────────────────────
REPO_URL="https://github.com/sena-design-studio/hs-lp-generator.git"
INSTALL_DIR="$HOME/.latigid/hs-lp-generator"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
log()     { echo -e "${GREEN}✓${NC} $1"; }
warn()    { echo -e "${YELLOW}!${NC} $1"; }
error()   { echo -e "${RED}✗${NC} $1"; }
header()  { echo -e "\n${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"; echo -e "  ${BOLD}$1${NC}"; echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"; }
section() { echo -e "\n${BOLD}$1${NC}"; echo -e "  $2\n"; }

clear
header "Latigid LP Generator — Installer"

# ─── Step 1: Requirements ─────────────────────────────────────────────────────
section "Step 1/6" "Checking requirements..."

if ! command -v node &> /dev/null; then
  error "Node.js not found. Install from https://nodejs.org then re-run."
  exit 1
fi
log "Node.js $(node -v) found"

if ! command -v git &> /dev/null; then
  error "Git not found. Run: xcode-select --install"
  exit 1
fi
log "Git found"

# ─── Step 2: Clone or update ──────────────────────────────────────────────────
section "Step 2/6" "Installing MCP server..."

mkdir -p "$HOME/.latigid"
if [ -d "$INSTALL_DIR/.git" ]; then
  warn "Already installed — pulling latest updates..."
  cd "$INSTALL_DIR" && git pull --quiet origin main
  log "Updated to latest version"
else
  log "Cloning repository..."
  git clone --quiet "$REPO_URL" "$INSTALL_DIR"
  log "Repository cloned"
fi

cd "$INSTALL_DIR"
log "Installing Node dependencies..."
npm install --quiet
log "Dependencies ready"

# ─── Step 3: Anthropic API Key ────────────────────────────────────────────────
section "Step 3/6" "Anthropic API Key (for wireframe analysis and web search)"

echo -e "  You need a personal Anthropic API key."
echo -e "  This keeps your usage separate from the rest of the team."
echo ""
echo -e "  ${BOLD}1. Open this URL in your browser:${NC}"
echo -e "     https://console.anthropic.com/settings/keys"
echo -e "  ${BOLD}2. Click 'Create Key', name it 'LP Generator'${NC}"
echo -e "  ${BOLD}3. Copy the key (starts with sk-ant-)${NC}"
echo -e "  ${BOLD}4. Paste it below and press Enter${NC}"
echo ""
printf "  Your Anthropic API key: "
read -r ANTHROPIC_KEY

# Basic validation
if [[ "$ANTHROPIC_KEY" != sk-ant-* ]]; then
  warn "Key doesn't look right (should start with sk-ant-) — saving anyway, you can update .env later."
else
  log "Anthropic API key looks good"
fi

# ─── Step 4: Write .env ───────────────────────────────────────────────────────
section "Step 4/6" "Configuring environment..."

write_env() {
  local onedrive_path="$1"
  cat > "$INSTALL_DIR/.env" << EOF
# Latigid LP Generator — Environment Configuration
# Auto-generated by installer. Do not edit unless instructed.

# HubSpot OAuth App
HS_APP_ID=34847043
HS_CLIENT_ID=1071c471-d9d3-48e6-9c00-566801d5132c
HS_CLIENT_SECRET=REPLACE_WITH_SECRET
HS_REDIRECT_URI=https://auth.latigid.dev/oauth/callback

# Remote auth server
REMOTE_AUTH_URL=https://auth.latigid.dev
AUTH_SECRET=REPLACE_WITH_SECRET

# Pexels API (shared)
PEXELS_API_KEY=apdLrgHDvp6MjgeJSE2mmmQ3ddZYnjKIKnwCh2e8rul6hvE5yh5BtGZw

# Anthropic API (personal — do not share)
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}

# OneDrive shared folder
ONEDRIVE_PATH=${onedrive_path}
EOF
}

if [ -f "$INSTALL_DIR/.env" ]; then
  # Patch existing .env
  if grep -q "localhost" "$INSTALL_DIR/.env"; then
    warn "Fixing redirect URI..."
    sed -i '' 's|HS_REDIRECT_URI=http://localhost:3000/oauth/callback|HS_REDIRECT_URI=https://auth.latigid.dev/oauth/callback|g' "$INSTALL_DIR/.env"
  fi
  # Update Anthropic key if provided
  if [ -n "$ANTHROPIC_KEY" ]; then
    if grep -q "^ANTHROPIC_API_KEY=" "$INSTALL_DIR/.env"; then
      sed -i '' "s|^ANTHROPIC_API_KEY=.*|ANTHROPIC_API_KEY=$ANTHROPIC_KEY|" "$INSTALL_DIR/.env"
    else
      echo "ANTHROPIC_API_KEY=$ANTHROPIC_KEY" >> "$INSTALL_DIR/.env"
    fi
    log "Anthropic API key saved to .env"
  fi
  log ".env updated"
else
  write_env ""
  log ".env created"
fi

# ─── Step 5: OneDrive detection ───────────────────────────────────────────────
section "Step 5/6" "Setting up shared template library (OneDrive)..."

DETECTED_ONEDRIVE=""
for candidate in \
  "$HOME/Library/CloudStorage/OneDrive-LATIGIDLDA/MCP Claude - Documents" \
  "$HOME/OneDrive - LATIGID LDA/MCP Claude - Documents" \
  "$HOME/OneDrive/MCP Claude - Documents"; do
  if [ -d "$candidate" ]; then
    DETECTED_ONEDRIVE="$candidate"
    break
  fi
done

if [ -n "$DETECTED_ONEDRIVE" ]; then
  echo -e "  ${GREEN}Found OneDrive folder:${NC}"
  echo -e "  ${BOLD}$DETECTED_ONEDRIVE${NC}\n"
  read -p "  Use this folder? [Y/n] " confirm
  confirm=${confirm:-Y}
  if [[ "$confirm" =~ ^[Yy]$ ]]; then
    ONEDRIVE_PATH="$DETECTED_ONEDRIVE"
    log "OneDrive path confirmed"
  else
    DETECTED_ONEDRIVE=""
  fi
fi

if [ -z "$DETECTED_ONEDRIVE" ]; then
  echo -e "  ${YELLOW}OneDrive folder not found automatically.${NC}"
  echo ""
  echo -e "  ${BOLD}Drag your 'MCP Claude - Documents' folder${NC}"
  echo -e "  from Finder into this Terminal window, then press Enter:"
  echo ""
  printf "  > "
  read -r raw_path
  ONEDRIVE_PATH=$(echo "$raw_path" | sed "s/^[[:space:]'\"]*//;s/[[:space:]'\"]*$//")

  if [ ! -d "$ONEDRIVE_PATH" ]; then
    error "Folder not found: $ONEDRIVE_PATH"
    error "Make sure OneDrive is synced and try again."
    exit 1
  fi
  log "OneDrive path set"
fi

# Validate subfolders
MISSING_FOLDERS=()
for folder in "lp-theme-generic" "lp-theme-programme" "client-images" "generated-themes"; do
  if [ ! -d "$ONEDRIVE_PATH/$folder" ]; then
    MISSING_FOLDERS+=("$folder")
  fi
done
if [ ${#MISSING_FOLDERS[@]} -gt 0 ]; then
  warn "Some folders missing from OneDrive (may still be syncing):"
  for f in "${MISSING_FOLDERS[@]}"; do echo -e "    · $f"; done
fi

# Save to .env
if grep -q "^ONEDRIVE_PATH=" "$INSTALL_DIR/.env"; then
  sed -i '' "s|^ONEDRIVE_PATH=.*|ONEDRIVE_PATH=$ONEDRIVE_PATH|" "$INSTALL_DIR/.env"
else
  echo "ONEDRIVE_PATH=$ONEDRIVE_PATH" >> "$INSTALL_DIR/.env"
fi
log "ONEDRIVE_PATH saved"

# Create symlinks
for folder in "lp-theme-generic" "lp-theme-programme" "generated-themes" "client-images"; do
  LINK="$INSTALL_DIR/$folder"
  TARGET="$ONEDRIVE_PATH/$folder"
  [ -L "$LINK" ] && rm "$LINK"
  if [ -d "$TARGET" ]; then
    ln -s "$TARGET" "$LINK"
    log "Linked $folder → OneDrive"
  else
    warn "$folder not in OneDrive yet — re-run installer after sync"
  fi
done

# ─── Step 6: Claude Desktop config ────────────────────────────────────────────
section "Step 6/6" "Configuring Claude Desktop..."

CLAUDE_CONFIG="$HOME/Library/Application Support/Claude/claude_desktop_config.json"
mkdir -p "$(dirname "$CLAUDE_CONFIG")"
[ -f "$CLAUDE_CONFIG" ] && cp "$CLAUDE_CONFIG" "$CLAUDE_CONFIG.bak" && log "Backed up existing Claude config"

node -e "
const fs = require('fs');
const configPath = process.argv[1];
let config = {};
try { config = JSON.parse(fs.readFileSync(configPath, 'utf8')); } catch {}
config.mcpServers = config.mcpServers || {};
config.mcpServers['hs-lp-generator'] = {
  command: 'node',
  args: ['$INSTALL_DIR/index.js']
};
fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
" "$CLAUDE_CONFIG"

log "Claude Desktop configured"

# ─── Done ─────────────────────────────────────────────────────────────────────
header "Installation complete! 🎉"

echo -e "  ${BOLD}Next steps:${NC}"
echo ""
echo -e "  1. ${BOLD}Get your secrets from Filipe${NC} (via Slack) and update:"
echo -e "     $INSTALL_DIR/.env"
echo -e "     Fill in: HS_CLIENT_SECRET and AUTH_SECRET"
echo ""
echo -e "  2. ${BOLD}Restart Claude Desktop${NC} — Cmd+Q then reopen"
echo ""
echo -e "  3. ${BOLD}Connect HubSpot${NC} — ask Claude:"
echo -e "     ${GREEN}\"List the themes in portal 2662575\"${NC}"
echo -e "     Claude will open the auth page automatically."
echo ""
echo -e "  4. ${BOLD}You're ready!${NC} Open the LP Generator project in Claude."
echo ""
read -p "  Press Enter to close..."
